sudo: required

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install rpm createrepo mock'
  - 'sudo apt-get install make debhelper reprepro cowbuilder'
  - 'sudo apt-get install debian-archive-keyring'
  - 'wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/d/debian-archive-keyring/debian-archive-keyring_2017.5_all.deb && sudo dpkg -i debian-archive-keyring_2017.5_all.deb' 

matrix:
  fast_finish: false
  include:

  -
    os: linux
    env:
      DIST=jessie
      OPTS=COW_OPTS\=--debootstrapopts\=--keyring\=/etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg
  -
    os: linux
    env:
      DIST=stretch
      OPTS=COW_OPTS\=--debootstrapopts\=--keyring\=/etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg
  -
    os: linux
    env:
      DIST=zesty
      OPTS=DEB_MIRROR\=http://us-central1.gce.archive.ubuntu.com/ubuntu

script:
  - make deb_chroot DIST=${DIST} ${OPTS}
