sudo: required

before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install rpm createrepo mock'
  - 'sudo apt-get install make debhelper reprepro cowbuilder'
  - 'sudo apt-get install debian-archive-keyring'
  - 'wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/d/debian-archive-keyring/debian-archive-keyring_2017.6_all.deb && sudo dpkg -i debian-archive-keyring_2017.6_all.deb' 

matrix:
  fast_finish: false
  include:

  -
    os: linux
    env:
      DIST=stretch
      OPTS=COW_OPTS\=--debootstrapopts\=--keyring\=/etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg SUDO\=sudo >/tmp/logs 2>&1;ret=$?;if [ $ret -ne 0 ];then tail -n 1000 /tmp/logs;exit $ret;fi
  -
    os: linux
    env:
      DIST=artful
      OPTS=DEB_MIRROR\=http://us-central1.gce.archive.ubuntu.com/ubuntu SUDO=sudo >/tmp/logs 2>&1;ret=$?;if [ $ret -ne 0 ];then tail -n 1000 /tmp/logs;exit $ret;fi

script:
  - make deb_chroot DIST=${DIST} ${OPTS} | tail -n 2000
