# Maintainer Information
MAINTAINER       := anonymous
MAINTAINER_EMAIL := anonymous@dev

# Package Origin Configuration
PKG_ORG         := amk
PKG_ORIGIN      := anonymous@dev
GPG_KEY         :=

# Repository Settings
DEB_REPO_COMPONENT := main

# Mirror Configuration
DEB_MIRROR      := https://ftp.debian.org/debian/
UBU_MIRROR      := https://archive.ubuntu.com/ubuntu/

# Repository Configuration
define DEB_REPO_CONFIG
Origin: $(PKG_ORIGIN)
Label: $(PKG_ORIGIN)
Suite: $(DIST)
Codename: $(DIST)
Version: 3.1
Architectures: $(ARCH)
Components: $(DEB_REPO_COMPONENT)
Description: Repository containing misc packages
SignWith: $(GPG_KEY)
endef

export DEB_REPO_CONFIG 
