# Name of the maintainer
MAINTAINER := Pierre-Francois Carpentier

# Email of the maintainer
MAINTAINER_EMAIL := carpentier.pf@gmail.com

# Origin ID (2 or 3 letters ID of origin)
PKG_ORG := kw

# Origin of the packages (full name)
PKG_ORIGIN := kakwa

GPG_KEY := kakwa

# repo component (main/contrib/non-free/universe/etc)
DEB_REPO_COMPONENT := main

# Definition of the debian repository configuration
# "Codename: $(DIST)" and "Components: $(DEB_REPO_COMPONENT)"
# should not be modified.
define DEB_REPO_CONFIG
Origin: $(PKG_ORIGIN)
Label: $(PKG_ORIGIN)
Suite: $(DIST)
Codename: $(DIST)
Version: 3.1
Architectures: $(shell dpkg --print-architecture)
Components: $(DEB_REPO_COMPONENT)
Description: Repository containing misc packages
SignWith: $(GPG_KEY)
endef


export DEB_REPO_CONFIG
