#!/bin/sh

set -e

GROUP=mock

case "$1" in
configure)
	if ! getent group $GROUP >/dev/null ; then
		groupadd --system $GROUP
	fi
	for dir in /var/lib/mock /var/cache/mock; do
		if ! dpkg-statoverride --list $dir >/dev/null; then
			dpkg-statoverride --update --add root $GROUP 02775 $dir
		fi
	done
	;;
esac

#DEBHELPER#

exit 0
